2022320070 전철우 3주차 과제 제출
KWEBofficial/241R-frontend pull request #145
Opened 2024-04-16 14:23 UTC by jcwoo1204

2주차 과제 떄 계속해서 파일에 문제가 생겨서 깃헙 포크하는 과정을 처음부터 다시 진행했습니디ㅏ.
1,2주차 과제 pull request 했던게 사라져서 같이 봐주시면 감사하겠습니다.

2024-04-27 13:22 UTC, wonjuneee requested changes
p21의 h1태그가 중앙에 정렬되도록 수정해주세요.

2024-04-30 09:01 UTC, jcwoo1204 commented
수정 완료했습니다! 확인 부탁드립니다. 감사합니다.

2024-05-03 09:52 UTC, wonjuneee approved these changes
확인했습니다. LGTM!

2024-05-03 09:52 UTC, wonjuneee commented on p21/text-styling.css
> +#current-chapter{
선택자 우선 순위가 존재하기 때문에 렌더링에는 문제가 없습니다.
하지만 #current-chapter > .chapter-name로 구체적인 선택자를 통해 하나의 element에 중복된 속성을 매기지 않는 것이 더욱 권장됩니다.

2024-05-03 09:53 UTC, closed without merging