2021320025 신태현 4주차 과제
KWEBofficial/241R-frontend pull request #179
Opened 2024-05-12 03:41 UTC by Swinj

.

2024-05-14 08:20 UTC, lsjbh45 requested changes
Exercise 2.3에서 버튼의 href 연결이 되지 않았습니다! 확인 후 다시 제출해주세요.

2024-05-26 01:56 UTC, Swinj commented
> Exercise 2.3에서 버튼의 href 연결이 되지 않았습니다! 확인 후 다시 제출해주세요.

수정했습니다!

2024-05-27 13:44 UTC, lsjbh45 requested changes
4주차 확인되었습니다!

5주차 과제는 Exercise 3.1의 작성이 잘못되었습니다! 아래를 참고해서 수정해 주세요.
Exercise 3.1: 정수에 대해서만 true를 반환해야 합니다.

2024-05-28 04:40 UTC, Swinj commented
> 4주차 확인되었습니다!
> 
> 5주차 과제는 Exercise 3.1의 작성이 잘못되었습니다! 아래를 참고해서 수정해 주세요. Exercise 3.1: 정수에 대해서만 true를 반환해야 합니다.

수정했습니다!

2024-06-23 11:00 UTC, LineNo2 approved these changes
잘하셨습니다.
3.1번은 말씀드린 부분 참고하셔서, 다음에 이와 비슷한 상황에 처하시면 해당 함수 사용하시면 되겠습니다.
한 학기 동안 과제하느라 고생 많으셨고, 즐겁고 보람찬 방학 보내시길 바라겠습니다~~

2024-06-23 11:00 UTC, LineNo2 commented on p31/script.js
> +    if(x%1==0&&x>=1&&x<=9)return true;
이전에 말씀드린 문제가 아직 존재합니다.
js에 존재하는 `Number.isInteger` 함수를 사용하시면, `true` 와 같은 invalid한 값에 `true`를 반환하는 현상을 막을 수 있습니다.

2024-06-23 11:00 UTC, LineNo2 commented on p42/times-table.js
지금도 좋은 구현이지만, 반복문을 사용하시는 방법도 있습니다!

2024-06-23 11:00 UTC, closed without merging