2022100124 권서은 4주차 과제
KWEBofficial/241R-frontend pull request #180
Opened 2024-05-12 03:48 UTC by thunnie920

4주차 과제 제출합니다

2024-05-14 08:22 UTC, lsjbh45 requested changes
Exercise 2.3과 flex, grid 연습 파일이 확인되지 않습니다! 확인 후에 다시 제출해주세요.

2024-05-15 03:54 UTC, thunnie920 commented
다시 제출했습니다!

2024-05-16 05:46 UTC, lsjbh45 commented
아직도 Exercise 2.3 작업하신 부분을 확인할 수가 없는 상태입니다..
로컬에서 파일이 제대로 커밋된 상태인지, 해당 내역이 github repo에 push었는지 다시 확인 부탁드립니다!
참고로 명령어는 다음과 같습니다.
```bash
git add p23/index.html p23/scroll-button.css
git commit -m "message"
git push
```

2024-05-16 05:46 UTC, lsjbh45 requested changes
아직도 Exercise 2.3 작업하신 부분을 확인할 수가 없는 상태입니다..
로컬에서 파일이 제대로 커밋된 상태인지, 해당 내역이 github repo에 push었는지 다시 확인 부탁드립니다!
참고로 명령어는 다음과 같습니다.
```bash
git add p23/index.html p23/scroll-button.css
git commit -m "message"
git push
```

2024-05-16 06:29 UTC, thunnie920 commented
누락된 것 같아요! 다시 제출했습니다

2024-05-16 07:42 UTC, lsjbh45 approved these changes
확인했습니다!

2024-05-16 07:42 UTC, closed without merging