2023320006 김민재 4주차 과제 제
KWEBofficial/241R-frontend pull request #187
Opened 2024-05-12 09:40 UTC by kmj200392

2024-05-14 08:29 UTC, LineNo2 requested changes
2.4 말씀드린부분만 수정해서 다시 올려주세요~~

2024-05-14 08:29 UTC, LineNo2 commented on p24/responsive-color-page.css
작은 쪽 조건은 걸지 않으셔도 됩니다.
`@media only screen and(max-width: 599px){`을 안넣고, `body{background-color: skyblue;}`만 작성하셔도 완벽하게 작동합니다.

2024-05-27 13:41 UTC, lsjbh45 requested changes
4주차 확인되었습니다!

5주차 과제는 Exercise 3.1의 작성이 잘못되었습니다! 아래를 참고해서 수정해 주세요.
Exercise 3.1: 정수에 대해서만 true를 반환해야 합니다.

2024-06-23 10:05 UTC, LineNo2 approved these changes
확인했습니다.
한 학기동안 스터디 들으시고 과제하시느라 고생 많으셨습니다!
즐겁고 보람찬 방학 되시길 바랍니다~~

2024-06-23 10:07 UTC, closed without merging