2024320178 김한성 5주차 과제 제출
KWEBofficial/241R-frontend pull request #195
Opened 2024-05-17 05:05 UTC by hansungk-ku

2024-05-27 13:28 UTC, lsjbh45 requested changes
Exercise 3.3의 경우에는, 작성하신 대로 해도 문제는 없으나, object literal 내부에 method를 구현하는 것이 문제의 의도입니다. 다시 한 번 작성해 보시는 것을 권장드립니다!

2024-06-06 16:25 UTC, hansungk-ku commented
수정하였습니다!

2024-06-06 16:26 UTC, hansungk-ku commented
> Exercise 3.3의 경우에는, 작성하신 대로 해도 문제는 없으나, object literal 내부에 method를 구현하는 것이 문제의 의도입니다. 다시 한 번 작성해 보시는 것을 권장드립니다!

수정하였습니다!

2024-06-07 00:35 UTC, lsjbh45 approved these changes
LGTM!

2024-06-07 00:35 UTC, closed without merging