2022100124 권서은 5주차 과제 제출
KWEBofficial/241R-frontend pull request #197
Opened 2024-05-22 03:38 UTC by thunnie920

5주차 과제 제출합니다!

2024-05-27 13:23 UTC, lsjbh45 requested changes
Exercise 3.1의 작성이 잘못되었습니다! 아래를 참고해서 수정해 주세요.

Exercise 3.1: 정수에 대해서만 true를 반환해야 합니다.

2024-05-28 09:17 UTC, thunnie920 commented
다시 제출 드립니다!

2024-06-09 09:42 UTC, thunnie920 commented
6주차 과제 제출합니다.

2024-06-23 10:01 UTC, LineNo2 approved these changes
확인했습니다.
한 학기동안 매번 출석하시고 과제하시느라 고생 많으셨습니다!
스터디 들어주셔서 감사하고, 즐거운 방학 보내시길 바라겠습니다~~

2024-06-23 10:02 UTC, closed without merging