2023320159 박세린 5주차 과제 제출
KWEBofficial/241R-frontend pull request #208
Opened 2024-05-26 15:00 UTC by serin4103

2024-05-27 13:02 UTC, lsjbh45 requested changes
Exercise 3.1, Exercise 3.2의 작성이 잘못되었습니다! 아래를 참고해서 수정해 주세요.

Exercise 3.1: `in` operand는 array element가 아닌 object property의 존재 확인에 사용됩니다.
Exercise 3.2: `getDivisors(196)` 예시를 통해 오류를 확인해 보세요.

2024-06-03 02:56 UTC, LineNo2 requested changes
3.1의 말씀드린부분만 수정해보시면 됩니다~~

2024-06-03 02:56 UTC, LineNo2 commented on p31/script.js
`isValidNumber(true)`인 경우를 확인해주세요. 이는 `true == 1`이 `true`로 evaluate되기 때문입니다. 이를 방지하기위해선 어떤 비교 연산자를 사용해야할까요?

2024-06-03 02:56 UTC, LineNo2 commented on p32/script.js
정답입니다! 다만 채점 기준이 아닌 일부 테스트케이스에 대해서는 의도하지 않은 출력을 확인했습니다. 일단 이 코드 자체는 정답이니 가볍게 읽어봐주세요.
`getDivisors(1)`을 실행시키면, 다음과 같은 결과가 나옵니다 : `[1,1,1]`.
이렇게 중복된 원소를 배열에서 제거하고 싶으시다면, 다음과 같은 방법을 사용하시면 됩니다 : 
```javascript
divisors = [...new Set(divisors)];
```
이 코드를 *적당한 곳*에 넣으시면, 중복이 제거될겁니다.
`Set`을 통해 `divisors`안에 있는 원소들을 집합에 넣어 중복을 제거한 후, `...` 연산자를 통해 배열 안의 원소들을 *풀어줍니다*. 다음과 같은 코드를 수행해보시면, `...`연산자가 무엇을 하는 친구인지 감이 오실겁니다.
```javascript
let a = [1,2,3];
[...a,...a]
```

2024-06-23 09:55 UTC, LineNo2 requested changes
~ 4.5까지 확인 완료했습니다.
생성형 AI 사용하셔도 되니, 4.6 과제 수행하시고 대신 그 로직은 이해하실 수 있도록 노력해보시면 좋을 것 같습니다!

2024-07-01 08:58 UTC, lsjbh45 requested changes
작성해 주신 평가시험 대체 과제 1번 확인했습니다. 다만 평가시험에 참여하지 않으셨기 때문에, 2번 과제도 함께 수행해 주셔야 합니다! exam 폴더의 README 파일을 참고해서 작성해 주세요.

2024-07-01 15:19 UTC, serin4103 commented
안녕하세요, 본시험에 참여하였는데 다시 확인해주실 수 있을까요? 감사합니다.

2024년 7월 1일 (월) 오후 5:58, Seungjik Lee ***@***.***>님이 작성:

> ***@***.**** requested changes on this pull request.
>
> 작성해 주신 평가시험 대체 과제 1번 확인했습니다. 다만 평가시험에 참여하지 않으셨기 때문에, 2번 과제도 함께 수행해 주셔야
> 합니다! exam 폴더의 README 파일을 참고해서 작성해 주세요.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KWEBofficial/241R-frontend/pull/208#pullrequestreview-2150819063>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2IMN3VF52QAXOH5VYNHL4DZKEK5HAVCNFSM6AAAAABIJ3XKSSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNJQHAYTSMBWGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-02 00:58 UTC, lsjbh45 approved these changes
안녕하세요, 수행해주신 1번 과제만으로 충분히 1학기 과정 마무리되는 것으로 정정하겠습니다! 처음 진행하는 방식이다 보니 저희가 내부적으로 관리하면서 누락이 있었습니다. 이렇게 번거롭게 해 드려서 죄송하고, 한 학기동안 스터디 열심히 참여해 주셔서 감사합니다!

2024-07-02 00:58 UTC, closed without merging