2023320012 김한결 5주차 과제 제출
KWEBofficial/241R-frontend pull request #214
Opened 2024-05-30 07:05 UTC by eorkd

2024-06-03 02:21 UTC, LineNo2 commented on p31/script.js
`x % 1 === 0`으로 int인지 체크하는 것도 가능하지만, `Number.isInteger(x)` 을 사용한 방법도 가능합니다.

2024-06-03 02:33 UTC, LineNo2 requested changes
3.2 말씀드린 내용 수정하셔서 다시 제출해주시길바랍니다~~

2024-06-03 02:33 UTC, LineNo2 commented on p32/script.js
다음 케이스 확인 바랍니다.
```javascript
getDivisors(196)
(실행결과) > [1, 2, 4, 7, 28, 49, 98, 196]
(정답) > [1,2,4,7,14,28,49,98,196]
```
반복문의 종료 조건을 확인해보시면, 힌트를 얻으실 수 있을겁니다.

2024-06-23 09:52 UTC, LineNo2 requested changes
~ 4.3 번까지 확인 했습니다.
생성형 AI 사용해서 과제를 수행하셔도 되니(본인이 무슨 로직인지 이해할 수 있어야 합니다), ~4.6까지 과제 수행후 다시 리뷰 요청해주시면 감사하겠습니다.
리뷰 요청 늦게 확인한 점 죄송합니다!

2024-07-01 09:02 UTC, lsjbh45 approved these changes
작성해 주신 평가시험 대체 과제 1번 확인했습니다. 한 학기동안 고생 많으셨고, 스터디 열심히 참여해 주셔서 감사합니다. 즐거운 방학 보내세요!

2024-07-01 09:02 UTC, closed without merging