2021320030 박찬우 6,7주차 과제 제출
KWEBofficial/241R-frontend pull request #223
Opened 2024-06-09 14:36 UTC by onff02

감사합니다.
한 학기 동안 감사했습니다.

2024-06-21 06:00 UTC, LineNo2 requested changes
3.2 번 말씀드린 부분 수정해주세요~

2024-06-21 06:00 UTC, LineNo2 commented on p32/script.js
`sqrt.max`라는 함수는 존재하지 않습니다. 이 부분 다시 확인해주시길 바랍니다~

2024-06-24 12:50 UTC, onff02 commented on p32/script.js
수정했습니다.

2024-06-25 17:42 UTC, onff02 commented
시험 풀이도 업로드 했습니다. 확인부탁드립니다.

2024-07-01 09:02 UTC, lsjbh45 approved these changes
작성해 주신 평가시험 대체 과제 1번 확인했습니다. 한 학기동안 고생 많으셨고, 스터디 열심히 참여해 주셔서 감사합니다. 즐거운 방학 보내세요!

2024-07-01 09:02 UTC, closed without merging