2022320037 정성현 5-7주차  과제 제출
KWEBofficial/241R-frontend pull request #225
Opened 2024-06-14 05:01 UTC by ghjsh

2024-06-21 05:48 UTC, LineNo2 requested changes
말씀드린 부분만 수정해서 다시 올려주세요~~

2024-06-21 05:48 UTC, LineNo2 commented on p44/random-level-up.js
`document.getElementById('gauge-bar').style.length = 30 * level;` 부분에서 그냥 `number`타입으로 쓰시면 안됩니다. 뒤에 `px`이나 `%`를 붙여서 문자열 형태로 전달하시면 의도하신대로 작동할겁니다!

2024-06-22 21:04 UTC, ghjsh commented
수정 반영된 건가요?

2024-06-23 09:45 UTC, LineNo2 approved these changes
말씀드린 부분 수정하셔서 최종 제출 처리 하겠습니다
한 학기동안 스터디 듣고 과제 하시느라 고생 많으셨습니다!

2024-06-23 09:45 UTC, LineNo2 commented on p44/random-level-up.js
> +    document.getElementById('gauge-bar').style.length = 30 * level + "px";
`length`가 아니라 `width`로 하시고, `px` -> `%`로 바꾸시면 됩니다! 제가 `length`속성이 있는지 몰랐어서 헷갈린것같습니다. 혼란을 드려 죄송합니다.

2024-06-23 09:45 UTC, closed without merging