2020320149 박규태 2주차 과제 제
KWEBofficial/241R-frontend pull request #73
Opened 2024-04-04 04:03 UTC by kutarr

2024-04-08 11:34 UTC, lsjbh45 requested changes

2024-04-08 11:34 UTC, lsjbh45 commented on p12/index.html
Code 1.2를 참고해서 HTML 표준에 맞게 수정해 주세요!

2024-04-08 13:38 UTC, kutarr commented on p12/index.html
다시 수정했습니다.

2024-04-12 14:00 UTC, lsjbh45 approved these changes
LGTM! 2주차, 3주차 모두 확인했습니다.

2024-04-12 14:00 UTC, closed without merging