2023320152 김가희 2주차
KWEBofficial/241R-frontend pull request #79
Opened 2024-04-05 03:01 UTC by HEEKGH

2주차 과제 제출합니다.

2024-04-08 11:43 UTC, lsjbh45 requested changes

2024-04-08 11:43 UTC, lsjbh45 commented on p12/index.html
Code 1.2를 참고해서 HTML 표준에 맞게 수정해 주세요!

2024-04-08 12:48 UTC, LineNo2 commented on p11/index.html
> +    <img src= "./images/logo.png" //링크말고 저장된 이미지 가져온 것
HTML의 주석은 다음과 같은 방법으로 달 수 있습니다
```HTML
<h1> 저는
<!-- 주석을 달아주세요 -->
보입니다
</h1>
```

2024-04-12 09:11 UTC, HEEKGH commented on p12/index.html
수정했습니다!

2024-04-12 09:12 UTC, HEEKGH commented
3주차 과제 제출합니다.

2024-04-12 14:03 UTC, lsjbh45 approved these changes
LGTM! 2주차, 3주차 모두 확인했습니다.

2024-04-12 14:04 UTC, closed without merging