2023320104 최승현 2주차 과제 제출
KWEBofficial/241R-frontend pull request #95
Opened 2024-04-08 08:58 UTC by cshyun1031

2024-04-08 12:46 UTC, lsjbh45 requested changes
Exercise 1.2도 작성해 주세요!

2024-04-09 05:59 UTC, cshyun1031 commented
2023320104 최승현 exercise 1.2 제출 완료했습니다

2024-04-12 14:15 UTC, lsjbh45 requested changes
Exercise 1.2 내용은 잘 작성하셨습니다! 새로 파일을 만드는 것이 아니라, `p12/index.html`을 수정해서 올려주시면 됩니다.

2024-04-15 10:38 UTC, cshyun1031 commented
2023320104 최승현 3주차 과제 제출

2024-04-29 10:09 UTC, lsjbh45 approved these changes
3주차 과제 확인 완료했습니다!

2024-04-29 10:09 UTC, closed without merging